const String weather_api_key = '';
const String degree = '\u00B0';
const String unitSymbolCelsius = 'C';
const String unitSymbolFahrenheit = 'F';
const String metric = 'metric';
const String imperial = 'imperial';
const String iconPrefix = 'https://openweathermap.org/img/wn/';
const String iconSuffix = '@2x.png';
const cities = ['Athens', 'Berlin', 'Cairo', 'Chittagong', 'Dhaka', 'Jakarta', 'London', 'Los Angeles', 'Moscow', 'New York', 'Sydney', 'Sylhet', 'Tokyo'];